apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "KristaStudio.fullname" . }}-ngnixConfig
  namespace: {{ include "KristaStudio.namespace" . }}
  labels:
    {{- include "KristaStudio.labels" . | nindent 4 }} 
data:
  studio.conf: |-
    server {
    listen 80;
    server_name localhost studio.*;
    set $domain default.svc.cluster.local;
    set $proxy_host 127.0.0.1:3000;
    set $proxy_uri $uri;
    if ($uri ~ /api(/.*)$) {
    set $proxy_host platform.$domain:9991;
    set $proxy_uri $1$is_args$args;
    }
    if ($uri ~ /socket.io/) {
    set $proxy_uri "";
    }
    if ($uri ~ /app/kibana) {
    set $proxy_host kibana.$domain:5601;
    }
    if ($http_referer ~ ^https?://studio..*/app/kibana.*$) {
    set $proxy_host kibana.$domain:5601;
    set $proxy_uri $uri$is_args$args;
    }
    location / {
    proxy_pass http://$proxy_host$proxy_uri;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    }
    }
