{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "KristaStudio.serviceAccountName" . }}
  namespace: {{ include "KristaStudio.namespace" . }}
  labels:
    {{- include "KristaStudio.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
