kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: elasticsearch
  name: elasticsearch
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: elasticsearch